language: node_js
node_js:
  - "0.8"
  - "0.10"
before_script:
  - npm install -g grunt-cli
script:
  - grunt
notifications:
  recipients:
    - bhaveshdt@hotmail.com
  email:
    on_success: change
    on_failure: always